#!/bin/sh
# Start/stop odoo
### BEGIN INIT INFO
# Provides:          odoo
# Required-Start:    postgresql
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The main odoo process
# Description:       The odoo process that receives HTTP requests
#                    at port 8069
#
### END INIT INFO
#
# Author:       Pablo Barrientos <pabarrientos@hotmail.com>
#

PIDFILE=/var/run/odoo.pid

. /lib/lsb/init-functions

NAME=odoo
RUN_AS=`id -u odoo`
CMD=/home/odoo/odoo/11/start.sh
OPTS=

do_start() {
    start-stop-daemon --start --background --user $RUN_AS --pidfile $PIDFILE --chuid $RUN_AS --startas $CMD -- $OPTS
}

do_stop() {
    start-stop-daemon --stop --user $RUN_AS
}

case "$1" in
start)
    log_action_msg "Starting $NAME"
    do_start
        ;;
stop)
    log_action_msg "Stopping $NAME"
    do_stop
    ;;
restart)
    log_action_msg "Restarting $NAME"
    do_stop
    do_start
    ;;
*)
    log_action_msg "Usage: /etc/init.d/odoo {start|stop|restart}"
    exit 2
    ;;
esac
exit 0
